<?php

namespace AppBundle\Repository;

/**
 * ScreenshotsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ScreenshotsRepository extends \Doctrine\ORM\EntityRepository
{
}
